# Site settings
title: NistPagesTemplate
description: "To improve the electric grid, we must empower consumers. Join the effort to give all Americans the information they need to become active participants in their own power usage."

baseurl: "/NistPagesTemplate"
rooturl: ""

# Build settings
markdown: kramdown
permalink: pretty
exclude: [node_modules, gruntfile.js, package,json]
